### ISSUE TITLE
Fails to build on windows-gnu

### ISSUE THREAD

**Issue by Seeker14491** [nabijaczleweli/cargo-update#36]
Attempting to install fails with a vague error.

```
PS C:\Users\seekr> rustup show
Default host: x86_64-pc-windows-gnu

nightly-x86_64-pc-windows-gnu (default)
rustc 1.19.0-nightly (557967766 2017-05-26)
PS C:\Users\seekr> cargo install cargo-update
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing cargo-update v1.0.0
   Compiling unicode-xid v0.0.4
   Compiling unicode-width v0.1.4
   Compiling winapi-build v0.1.1
   Compiling bitflags v0.8.2
   Compiling array_tool v0.3.5
   Compiling regex-syntax v0.4.1
   Compiling pkg-config v0.3.9
   Compiling ansi_term v0.9.0
   Compiling vec_map v0.8.0
   Compiling unicode-normalization v0.1.4
   Compiling quote v0.3.15
   Compiling kernel32-sys v0.2.2
   Compiling strsim v0.6.0
   Compiling synom v0.11.3
   Compiling json v0.11.6
   Compiling utf8-ranges v1.0.0
   Compiling unicode-segmentation v1.2.0
   Compiling serde v1.0.8
   Compiling syn v0.11.11
   Compiling gcc v0.3.49
   Compiling tabwriter v1.0.3
   Compiling winapi v0.2.8
   Compiling embed-resource v1.1.1
   Compiling libc v0.2.23
   Compiling cargo-update v1.0.0
   Compiling rand v0.3.15
error: failed to run custom build command for `cargo-update v1.0.0`
process didn't exit successfully: `C:\Users\seekr\AppData\Local\Temp\cargo-install.ZgXCbqjBSiUy\release\build\cargo-update-87b2aa30f3df4201\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "The system cannot find the file specified." } }', src\libcore\result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build failed, waiting for other jobs to finish...
error: failed to compile `cargo-update v1.0.0`, intermediate artifacts can be found at `C:\Users\seekr\AppData\Local\Temp\cargo-install.ZgXCbqjBSiUy`

Caused by:
  build failed
```

**Comment by nabijaczleweli** [comment]
Does running with `RUST_BACKTRACE=1` give you a backtrace? If so, post it here.

**Comment by Seeker14491** [comment]
Yes, here it is:

```
stack backtrace:
   0: std::sys_common::backtrace::_print
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: embed_resource::windows_not_msvc::compile_resource
  10: build_script_build::main
  11: _rust_maybe_catch_panic
  12: std::rt::lang_start
  13: _tmainCRTStartup
  14: mainCRTStartup
  15: unit_addrs_search
```

**Comment by nabijaczleweli** [comment]
I uploaded a new version of `embed-resource` to crates so if you could attempt a re-install of cargo update so that it gets a new error message with that that'd be great.

**Comment by Seeker14491** [comment]
Here it is:

```
PS C:\Users\seekr> cargo install cargo-update
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing cargo-update v1.0.0
 Downloading embed-resource v1.1.2
   Compiling quote v0.3.15
   Compiling gcc v0.3.49
   Compiling semver-parser v0.7.0
   Compiling utf8-ranges v1.0.0
   Compiling unicode-segmentation v1.2.0
   Compiling regex-syntax v0.4.1
   Compiling pkg-config v0.3.9
   Compiling lazy_static v0.2.8
   Compiling void v1.0.2
   Compiling serde v1.0.8
   Compiling strsim v0.6.0
   Compiling array_tool v0.3.6
   Compiling matches v0.1.4
   Compiling unicode-bidi v0.3.2
   Compiling semver v0.6.0
   Compiling unicode-normalization v0.1.4
   Compiling unicode-width v0.1.4
   Compiling vec_map v0.8.0
   Compiling tabwriter v1.0.3
   Compiling libc v0.2.23
   Compiling unicode-xid v0.0.4
   Compiling json v0.11.6
   Compiling winapi-build v0.1.1
   Compiling rand v0.3.15
   Compiling memchr v1.0.1
   Compiling idna v0.1.2
   Compiling kernel32-sys v0.2.2
   Compiling embed-resource v1.1.2
   Compiling ansi_term v0.9.0
   Compiling cargo-update v1.0.0
   Compiling lazysort v0.1.1
   Compiling synom v0.11.3
   Compiling aho-corasick v0.6.3
   Compiling bitflags v0.8.2
   Compiling bitflags v0.7.0
   Compiling syn v0.11.11
   Compiling toml v0.4.1
   Compiling url v1.4.0
   Compiling unreachable v0.1.1
   Compiling cmake v0.1.24
   Compiling libz-sys v1.0.13
   Compiling curl-sys v0.3.11
error: failed to run custom build command for `cargo-update v1.0.0`
process didn't exit successfully: `C:\Users\seekr\AppData\Local\Temp\cargo-install.hkTLJgxvERtG\release\build\cargo-update-87b2aa30f3df4201\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Failed to execute windres: Error { repr: Os { code: 2, message: "The system cannot find the file specified." } }', src\libcore\result.rs:859
stack backtrace:
   0: std::sys_common::backtrace::_print
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: embed_resource::windows_not_msvc::compile_resource
  10: build_script_build::main
  11: _rust_maybe_catch_panic
  12: std::rt::lang_start
  13: _tmainCRTStartup
  14: mainCRTStartup
  15: unit_addrs_search

Build failed, waiting for other jobs to finish...
error: failed to compile `cargo-update v1.0.0`, intermediate artifacts can be found at `C:\Users\seekr\AppData\Local\Temp\cargo-install.hkTLJgxvERtG`

Caused by:
  build failed
```

**Comment by nabijaczleweli** [comment]
Well then eire's yer problem, get `windres` (dunno what kind of build you're running, but it's an element of binutils so it's in every derivative of MinGW (or anything linuxy, really)) and that should be this.

**Comment by Seeker14491** [comment]
I installed MinGW-w64, and I now get a different error about not having `make`. I'm going to try msys2 next, which I believe includes `make`.

```
PS C:\Users\seekr> cargo install cargo-update
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing cargo-update v1.0.0
   Compiling gcc v0.3.49
   Compiling unicode-segmentation v1.2.0
   Compiling ansi_term v0.9.0
   Compiling regex-syntax v0.4.1
   Compiling array_tool v0.3.6
   Compiling utf8-ranges v1.0.0
   Compiling serde v1.0.8
   Compiling pkg-config v0.3.9
   Compiling bitflags v0.7.0
   Compiling bitflags v0.8.2
   Compiling json v0.11.6
   Compiling unicode-xid v0.0.4
   Compiling embed-resource v1.1.2
   Compiling matches v0.1.4
   Compiling synom v0.11.3
   Compiling cargo-update v1.0.0
   Compiling unicode-bidi v0.3.2
   Compiling lazy_static v0.2.8
   Compiling winapi v0.2.8
   Compiling strsim v0.6.0
   Compiling unicode-normalization v0.1.4
   Compiling winapi-build v0.1.1
   Compiling void v1.0.2
   Compiling idna v0.1.2
   Compiling unreachable v0.1.1
   Compiling kernel32-sys v0.2.2
   Compiling libc v0.2.23
   Compiling unicode-width v0.1.4
   Compiling toml v0.4.1
   Compiling vec_map v0.8.0
   Compiling rand v0.3.15
   Compiling tabwriter v1.0.3
   Compiling memchr v1.0.1
   Compiling cmake v0.1.24
   Compiling curl-sys v0.3.11
   Compiling aho-corasick v0.6.3
   Compiling url v1.4.1
   Compiling libz-sys v1.0.13
   Compiling lazysort v0.1.1
   Compiling quote v0.3.15
   Compiling semver-parser v0.7.0
   Compiling libssh2-sys v0.2.6
   Compiling libgit2-sys v0.6.11
   Compiling syn v0.11.11
   Compiling semver v0.6.0
error: failed to run custom build command for `libz-sys v1.0.13`
process didn't exit successfully: `C:\Users\seekr\AppData\Local\Temp\cargo-install.UpE7d0Wmo3Pg\release\build\libz-sys-a0376854548c6a52\build-script-build` (exit code: 1)
--- stdout
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
HOST_CC = None
CC = None
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
PROFILE = Some("release")
running: "make" "-f" "win32/Makefile.gcc" "install" "prefix=/C/Users/seekr/AppData/Local/Temp/cargo-install.UpE7d0Wmo3Pg/release/build/libz-sys-0598af38eaebd697/out" "IMPLIB=" "INCLUDE_PATH=/C/Users/seekr/AppData/Local/Temp/cargo-install.UpE7d0Wmo3Pg/release/build/libz-sys-0598af38eaebd697/out/include" "LIBRARY_PATH=/C/Users/seekr/AppData/Local/Temp/cargo-install.UpE7d0Wmo3Pg/release/build/libz-sys-0598af38eaebd697/out/lib" "BINARY_PATH=/C/Users/seekr/AppData/Local/Temp/cargo-install.UpE7d0Wmo3Pg/release/build/libz-sys-0598af38eaebd697/out/bin"


failed to execute command: The system cannot find the file specified. (os error 2)
Is `make` not installed?



Build failed, waiting for other jobs to finish...
error: failed to compile `cargo-update v1.0.0`, intermediate artifacts can be found at `C:\Users\seekr\AppData\Local\Temp\cargo-install.UpE7d0Wmo3Pg`

Caused by:
  build failed
```

**Comment by nabijaczleweli** [comment]
MinGW-w64 includes `make` under the name `mingw32-make` (or `mingw64-make`) because it's bad.

**Comment by Seeker14491** [comment]
Indeed there was `mingw32-make`; I made a symbolic link to it named `make`, and now I get a different error.

```
PS C:\Users\seekr> cargo install cargo-update
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing cargo-update v1.0.0
   Compiling strsim v0.6.0
   Compiling array_tool v0.3.6
   Compiling quote v0.3.15
   Compiling winapi v0.2.8
   Compiling unicode-segmentation v1.2.0
   Compiling winapi-build v0.1.1
   Compiling unicode-xid v0.0.4
   Compiling utf8-ranges v1.0.0
   Compiling bitflags v0.7.0
   Compiling matches v0.1.4
   Compiling synom v0.11.3
   Compiling unicode-width v0.1.4
   Compiling serde v1.0.8
   Compiling json v0.11.6
   Compiling vec_map v0.8.0
   Compiling regex-syntax v0.4.1
   Compiling pkg-config v0.3.9
   Compiling lazy_static v0.2.8
   Compiling syn v0.11.11
   Compiling embed-resource v1.1.2
   Compiling kernel32-sys v0.2.2
   Compiling unicode-normalization v0.1.4
   Compiling cargo-update v1.0.0
   Compiling bitflags v0.8.2
   Compiling unicode-bidi v0.3.2
   Compiling semver-parser v0.7.0
   Compiling libc v0.2.23
   Compiling rand v0.3.15
   Compiling memchr v1.0.1
   Compiling semver v0.6.0
   Compiling idna v0.1.2
   Compiling aho-corasick v0.6.3
   Compiling toml v0.4.1
   Compiling gcc v0.3.49
   Compiling void v1.0.2
   Compiling lazysort v0.1.1
   Compiling unreachable v0.1.1
   Compiling ansi_term v0.9.0
   Compiling tabwriter v1.0.3
   Compiling url v1.4.1
   Compiling serde_derive_internals v0.15.1
   Compiling cmake v0.1.24
   Compiling curl-sys v0.3.11
   Compiling libz-sys v1.0.13
   Compiling libgit2-sys v0.6.11
   Compiling libssh2-sys v0.2.6
   Compiling serde_derive v1.0.8
error: failed to run custom build command for `libz-sys v1.0.13`
process didn't exit successfully: `C:\Users\seekr\AppData\Local\Temp\cargo-install.pfuheFYaJfvk\release\build\libz-sys-a0376854548c6a52\build-script-build` (exit code: 1)
--- stdout
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
HOST_CC = None
CC = None
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
PROFILE = Some("release")
running: "make" "-f" "win32/Makefile.gcc" "install" "prefix=/C/Users/seekr/AppData/Local/Temp/cargo-install.pfuheFYaJfvk/release/build/libz-sys-0598af38eaebd697/out" "IMPLIB=" "INCLUDE_PATH=/C/Users/seekr/AppData/Local/Temp/cargo-install.pfuheFYaJfvk/release/build/libz-sys-0598af38eaebd697/out/include" "LIBRARY_PATH=/C/Users/seekr/AppData/Local/Temp/cargo-install.pfuheFYaJfvk/release/build/libz-sys-0598af38eaebd697/out/lib" "BINARY_PATH=/C/Users/seekr/AppData/Local/Temp/cargo-install.pfuheFYaJfvk/release/build/libz-sys-0598af38eaebd697/out/bin"
gcc  -O3 -Wall -c -o adler32.o adler32.c
gcc  -O3 -Wall -c -o compress.o compress.c
gcc  -O3 -Wall -c -o crc32.o crc32.c
gcc  -O3 -Wall -c -o deflate.o deflate.c
gcc  -O3 -Wall -c -o gzclose.o gzclose.c
gcc  -O3 -Wall -c -o gzlib.o gzlib.c
gcc  -O3 -Wall -c -o gzread.o gzread.c
gcc  -O3 -Wall -c -o gzwrite.o gzwrite.c
gcc  -O3 -Wall -c -o infback.o infback.c
gcc  -O3 -Wall -c -o inffast.o inffast.c
gcc  -O3 -Wall -c -o inflate.o inflate.c
gcc  -O3 -Wall -c -o inftrees.o inftrees.c
gcc  -O3 -Wall -c -o trees.o trees.c
gcc  -O3 -Wall -c -o uncompr.o uncompr.c
gcc  -O3 -Wall -c -o zutil.o zutil.c
ar rcs libz.a adler32.o compress.o crc32.o deflate.o gzclose.o gzlib.o gzread.o gzwrite.o infback.o inffast.o inflate.o inftrees.o trees.o uncompr.o zutil.o
win32/Makefile.gcc:128: recipe for target 'install' failed


command did not execute successfully, got: exit code: 2



--- stderr
-z was unexpected at this time.
make: *** [install] Error 255

Build failed, waiting for other jobs to finish...
error: failed to compile `cargo-update v1.0.0`, intermediate artifacts can be found at `C:\Users\seekr\AppData\Local\Temp\cargo-install.pfuheFYaJfvk`

Caused by:
  build failed
```

**Comment by nabijaczleweli** [comment]
Look into that Makefile, see what uses the `-z` option, then probably update it or sth idk

**Comment by mati865** [comment]
Builds just fine in MSYS2 mingw64 shell with nightly rustc:
```
cargo install cargo-update --force
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing cargo-update v1.0.0
 Downloading array_tool v0.3.8
 Downloading unicode-bidi v0.3.3
   Compiling unicode-normalization v0.1.4
   Compiling ansi_term v0.9.0
   Compiling lazy_static v0.2.8
   Compiling libc v0.2.23
   Compiling embed-resource v1.1.2
   Compiling memchr v1.0.1
   Compiling regex-syntax v0.4.1
   Compiling strsim v0.6.0
   Compiling winapi-build v0.1.1
   Compiling kernel32-sys v0.2.2
   Compiling quote v0.3.15
   Compiling unicode-width v0.1.4
   Compiling unicode-segmentation v1.2.0
   Compiling tabwriter v1.0.3
   Compiling bitflags v0.7.0
   Compiling aho-corasick v0.6.3
   Compiling void v1.0.2
   Compiling unreachable v0.1.1
   Compiling winapi v0.2.8
   Compiling utf8-ranges v1.0.0
   Compiling matches v0.1.4
   Compiling unicode-bidi v0.3.3
   Compiling idna v0.1.2
   Compiling semver-parser v0.7.0
   Compiling semver v0.6.0
   Compiling json v0.11.6
   Compiling url v1.4.1
   Compiling array_tool v0.3.8
   Compiling gcc v0.3.49
   Compiling pkg-config v0.3.9
   Compiling rand v0.3.15
   Compiling cmake v0.1.24
   Compiling serde v1.0.8
   Compiling libgit2-sys v0.6.11
   Compiling libssh2-sys v0.2.6
   Compiling vec_map v0.8.0
   Compiling unicode-xid v0.0.4
   Compiling synom v0.11.3
   Compiling toml v0.4.1
   Compiling syn v0.11.11
   Compiling bitflags v0.8.2
   Compiling curl-sys v0.3.11
   Compiling serde_derive_internals v0.15.1
   Compiling cargo-update v1.0.0
   Compiling libz-sys v1.0.13
   Compiling serde_derive v1.0.8
   Compiling lazysort v0.1.1
   Compiling term_size v0.3.0
   Compiling atty v0.2.2
   Compiling thread-id v3.1.0
   Compiling thread_local v0.3.3
   Compiling regex v0.2.2
   Compiling clap v2.24.2
   Compiling git2 v0.6.5
    Finished release [optimized] target(s) in 1557.92 secs
   Replacing C:\Users\mati865\.cargo\bin\cargo-install-update.exe
   Replacing C:\Users\mati865\.cargo\bin\cargo-install-update-config.exe
```

**Comment by nabijaczleweli** [comment]
Well obviously it builds on MSYS2, that's my devenv, so if it builds on *anything* it's gonna be MSYS2.

**Comment by Seeker14491** [comment]
I've tried MSYS2, but I get another error:

```
$ cargo install cargo-update
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing cargo-update v1.0.0
   Compiling semver-parser v0.7.0
   Compiling regex-syntax v0.4.1
   Compiling strsim v0.6.0
   Compiling pkg-config v0.3.9
   Compiling serde v1.0.8
   Compiling void v1.0.2
   Compiling lazy_static v0.2.8
   Compiling libc v0.2.23
   Compiling embed-resource v1.1.2
   Compiling winapi-build v0.1.1
   Compiling memchr v1.0.1
   Compiling unicode-normalization v0.1.4
   Compiling ansi_term v0.9.0
   Compiling vec_map v0.8.0
   Compiling unreachable v0.1.1
   Compiling aho-corasick v0.6.3
   Compiling semver v0.6.0
   Compiling json v0.11.6
   Compiling bitflags v0.8.2
   Compiling utf8-ranges v1.0.0
   Compiling quote v0.3.15
   Compiling gcc v0.3.49
   Compiling matches v0.1.4
   Compiling kernel32-sys v0.2.2
   Compiling unicode-bidi v0.3.3
   Compiling winapi v0.2.8
   Compiling rand v0.3.15
   Compiling cargo-update v1.0.0
   Compiling bitflags v0.7.0
   Compiling array_tool v0.3.8
   Compiling idna v0.1.2
   Compiling lazysort v0.1.1
   Compiling unicode-width v0.1.4
   Compiling toml v0.4.1
   Compiling tabwriter v1.0.3
   Compiling unicode-xid v0.0.4
   Compiling unicode-segmentation v1.2.0
   Compiling synom v0.11.3
   Compiling syn v0.11.11
   Compiling url v1.4.1
   Compiling cmake v0.1.24
   Compiling curl-sys v0.3.11
   Compiling libz-sys v1.0.13
   Compiling libssh2-sys v0.2.6
   Compiling libgit2-sys v0.6.11
   Compiling serde_derive_internals v0.15.1
error: failed to run custom build command for `libssh2-sys v0.2.6`
process didn't exit successfully: `C:\Users\seekr\AppData\Local\Temp\cargo-install.QO8z6Fsp3LZx\release\build\libssh2-sys-4774f14c11dd08f6\build-script-build` (exit code: 101)
--- stdout
running: "cmake" "C:\\Users\\seekr\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\libssh2-sys-0.2.6\\libssh2" "-G" "MSYS Makefiles" "-DCRYPTO_BACKEND=WinCNG" "-DZLIB_INCLUDE_DIR=C:\\Users\\seekr\\AppData\\Local\\Temp\\cargo-install.QO8z6Fsp3LZx\\release\\build\\libz-sys-0598af38eaebd697\\out/include" "-DBUILD_SHARED_LIBS=OFF" "-DENABLE_ZLIB_COMPRESSION=ON" "-DCMAKE_INSTALL_LIBDIR=lib" "-DBUILD_EXAMPLES=OFF" "-DBUILD_TESTING=OFF" "-DCMAKE_INSTALL_PREFIX=C:\\Users\\seekr\\AppData\\Local\\Temp\\cargo-install.QO8z6Fsp3LZx\\release\\build\\libssh2-sys-0fb041a6ead1733a\\out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -m64" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -m64" "-DCMAKE_BUILD_TYPE=Release"

--- stderr
fatal: Not a git repository (or any of the parent directories): .git
CMake Error: Could not create named generator MSYS Makefiles

Generators
  Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.
  KDevelop3                    = Generates KDevelop 3 project files.
  KDevelop3 - Unix Makefiles   = Generates KDevelop 3 project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files.

thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', C:\Users\seekr\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.24\src\lib.rs:593
stack backtrace:
   0: std::sys_common::backtrace::_print
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: cmake::fail
   7: cmake::run
   8: cmake::Config::build
   9: build_script_build::main
  10: _rust_maybe_catch_panic
  11: std::rt::lang_start
  12: _tmainCRTStartup
  13: mainCRTStartup
  14: unit_addrs_search

Build failed, waiting for other jobs to finish...
```

**Comment by nabijaczleweli** [comment]
Fixing problems with dependencies is left as an exercise to the ~~reader~~ respective dependency's maintainer.

**Comment by torpak** [comment]
i had the same problem: your cmake version is too old.
deinstall msys cmake and install mingw64 cmake.
that fixed this problem for  me. but now i'm stuck at:
error[E0308]: mismatched types
   --> C:\Users\Someone\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-update-1.0.0\src/main.rs:108:52
    |
108 |                         Command::new("cargo").args(cfg.cargo_args()).arg(&package.name).status().unwrap()
    |                                                    ^^^^^^^^^^^^^^^^ expected &[_], found struct `std::vec::Vec`
    |
    = note: expected type `&[_]`
    = note:    found type `std::vec::Vec<std::string::String>`

error: aborting due to previous error


thread 'rustc' has overflowed its stack
error: failed to compile `cargo-update v1.0.0`, intermediate artifacts can be found at `D:\msys64\tmp\cargo-install.os6M3T9YoPzc`

Caused by:
  Could not compile `cargo-update`.

To learn more, run the command again with --verbose.

**Comment by nabijaczleweli** [comment]
What version of rustc do you have?

**Comment by torpak** [comment]
1.18 stable
But with 1.17 i had the same problem.

**Comment by nabijaczleweli** [comment]
Does this still persist with `v1.1.0`?

**Comment by torpak** [comment]
I will check on monday since i have no windows at home.

**Comment by torpak** [comment]
Interestingly i still get the same or nearly the same error:

     Running `rustc --crate-name cargo_install_update_config .cargo\\registry\\src\\github.com-1ecc6299db9ec823\\cargo-update-1.1.0\\src/main-config.rs --crate-type bin -C opt-level=3 -C metadata=7d9b6e7227534dba -C extra-filename=-7d9b6e7227534dba --out-dir D:\\msys64\\tmp\\cargo-install.5NSXMMZLoRAS\\release\\deps --emit=dep-info,link -L dependency=D:\\msys64\\tmp\\cargo-install.5NSXMMZLoRAS\\release\\deps --extern clap=D:\\msys64\\tmp\\cargo-install.5NSXMMZLoRAS\\release\\deps\\libclap-cba94ee84f2ed69e.rlib --extern serde=D:\\msys64\\tmp\\cargo-install.5NSXMMZLoRAS\\release\\deps\\libserde-24988083064175a6.rlib --extern json=D:\\msys64\\tmp\\cargo-install.5NSXMMZLoRAS\\release\\deps\\libjson-c538e225942f838d.rlib --extern semver=D:\\msys64\\tmp\\cargo-install.5NSXMMZLoRAS\\release\\deps\\libsemver-20bc9e232421fd21.rlib --extern toml=D:\\msys64\\tmp\\cargo-install.5NSXMMZLoRAS\\release\\deps\\libtoml-25b834c41fa63622.rlib --extern tabwriter=D:\\msys64\\tmp\\cargo-install.5NSXMMZLoRAS\\release\\deps\\libtabwriter-2791710dd0ffa83a.rlib --extern array_tool=D:\\msys64\\tmp\\cargo-install.5NSXMMZLoRAS\\release\\deps\\libarray_tool-587192ce2cf97e8b.rlib --extern lazysort=D:\\msys64\\tmp\\cargo-install.5NSXMMZLoRAS\\release\\deps\\liblazysort-41e739b0f13662f6.rlib --extern git2=D:\\msys64\\tmp\\cargo-install.5NSXMMZLoRAS\\release\\deps\\libgit2-0e6c3829186d3bb5.rlib --extern regex=D:\\msys64\\tmp\\cargo-install.5NSXMMZLoRAS\\release\\deps\\libregex-01bef483f0a4bf46.rlib --extern serde_derive=D:\\msys64\\tmp\\cargo-install.5NSXMMZLoRAS\\release\\deps\\serde_derive-6fe6955ef19701cd.dll --extern lazy_static=D:\\msys64\\tmp\\cargo-install.5NSXMMZLoRAS\\release\\deps\\liblazy_static-05c6535e411a431f.rlib --extern cargo_update=D:\\msys64\\tmp\\cargo-install.5NSXMMZLoRAS\\release\\deps\\libcargo_update-cf995208bd7f0489.rlib --cap-lints allow -L native=D:\\msys64\\tmp\\cargo-install.5NSXMMZLoRAS\\release\\build\\cargo-update-534dceee622f3979\\out -L native=D:\\msys64\\tmp\\cargo-install.5NSXMMZLoRAS\\release\\build\\libgit2-sys-93b695a18d8340a6\\out/lib -L native=D:\\msys64\\tmp\\cargo-install.5NSXMMZLoRAS\\release\\build\\libssh2-sys-1d0e05365f94c88c\\out/lib -L native=/usr/lib -L D:\\msys64\\tmp\\cargo-install.5NSXMMZLoRAS\\release\\build\\curl-sys-f37549b1b0d3bd44\\out/lib`
error[E0308]: mismatched types
   --> .cargo\registry\src\github.com-1ecc6299db9ec823\cargo-update-1.1.0\src/main.rs:105:39
    |
105 |                                 .args(cfg.cargo_args())
    |                                       ^^^^^^^^^^^^^^^^ expected &[_], found struct `std::vec::Vec`
    |
    = note: expected type `&[_]`
    = note:    found type `std::vec::Vec<std::string::String>`

error: aborting due to previous error


thread 'rustc' has overflowed its stack
error: failed to compile `cargo-update v1.1.0`, intermediate artifacts can be found at `D:\msys64\tmp\cargo-install.5NSXMMZLoRAS`

Caused by:
  Could not compile `cargo-update`.

Caused by:
  process didn't exit successfully: `rustc --crate-name cargo_install_update .cargo\registry\src\github.com-1ecc6299db9ec823\cargo-update-1.1.0\src/main.rs --crate-type bin -C opt-level=3 -C metadata=caa5f128b8ccaed3 -C extra-filename=-caa5f128b8ccaed3 --out-dir D:\msys64\tmp\cargo-install.5NSXMMZLoRAS\release\deps --emit=dep-info,link -L dependency=D:\msys64\tmp\cargo-install.5NSXMMZLoRAS\release\deps --extern clap=D:\msys64\tmp\cargo-install.5NSXMMZLoRAS\release\deps\libclap-cba94ee84f2ed69e.rlib --extern serde=D:\msys64\tmp\cargo-install.5NSXMMZLoRAS\release\deps\libserde-24988083064175a6.rlib --extern json=D:\msys64\tmp\cargo-install.5NSXMMZLoRAS\release\deps\libjson-c538e225942f838d.rlib --extern semver=D:\msys64\tmp\cargo-install.5NSXMMZLoRAS\release\deps\libsemver-20bc9e232421fd21.rlib --extern toml=D:\msys64\tmp\cargo-install.5NSXMMZLoRAS\release\deps\libtoml-25b834c41fa63622.rlib --extern tabwriter=D:\msys64\tmp\cargo-install.5NSXMMZLoRAS\release\deps\libtabwriter-2791710dd0ffa83a.rlib --extern array_tool=D:\msys64\tmp\cargo-install.5NSXMMZLoRAS\release\deps\libarray_tool-587192ce2cf97e8b.rlib --extern lazysort=D:\msys64\tmp\cargo-install.5NSXMMZLoRAS\release\deps\liblazysort-41e739b0f13662f6.rlib --extern git2=D:\msys64\tmp\cargo-install.5NSXMMZLoRAS\release\deps\libgit2-0e6c3829186d3bb5.rlib --extern regex=D:\msys64\tmp\cargo-install.5NSXMMZLoRAS\release\deps\libregex-01bef483f0a4bf46.rlib --extern serde_derive=D:\msys64\tmp\cargo-install.5NSXMMZLoRAS\release\deps\serde_derive-6fe6955ef19701cd.dll --extern lazy_static=D:\msys64\tmp\cargo-install.5NSXMMZLoRAS\release\deps\liblazy_static-05c6535e411a431f.rlib --extern cargo_update=D:\msys64\tmp\cargo-install.5NSXMMZLoRAS\release\deps\libcargo_update-cf995208bd7f0489.rlib --cap-lints allow -L native=D:\msys64\tmp\cargo-install.5NSXMMZLoRAS\release\build\cargo-update-534dceee622f3979\out -L native=D:\msys64\tmp\cargo-install.5NSXMMZLoRAS\release\build\libgit2-sys-93b695a18d8340a6\out/lib -L native=D:\msys64\tmp\cargo-install.5NSXMMZLoRAS\release\build\libssh2-sys-1d0e05365f94c88c\out/lib -L native=/usr/lib -L D:\msys64\tmp\cargo-install.5NSXMMZLoRAS\release\build\curl-sys-f37549b1b0d3bd44\out/lib` (exit code: 3221225477)

**Comment by mati865** [comment]
@torpak are you using Rust from MINGW64 shell with toolchain installed (`pacman -S --needed mingw-w64-x86_64-toolchain`)?

**Comment by torpak** [comment]
i used rustup (under msys) to install stable-x86_64-pc-windows-gnu.

**Comment by nabijaczleweli** [comment]
Alright, I updated to `1.18.0` and cleared my lockfile, but the error didn't appear.

Try changing that line to `.args(&cfg.cargo_args())` or `.args(&cfg.cargo_args()[..])` and it'll probably work, hopefully?

**Comment by torpak** [comment]
the second works :-)

**Comment by nabijaczleweli** [comment]
Fixed in [`v1.1.1`](https://github.com/nabijaczleweli/cargo-update/releases/tag/v1.1.1).

**Comment by torpak** [comment]
v1.1.1 fixes my problem. What about you @Seeker14491 ?

**Comment by Seeker14491** [comment]
@torpak, I've since switched to using the MSVC toolchain, with which I had no problems installing this. I don't have MSYS2 on my computer at the moment, so I can't test this fix right now. The only reason I was using the GNU toolchain was because I was waiting for Rust to properly support VS2017, which [has happened](https://github.com/rust-lang/rust/pull/42225).

It would be nice if there were directions somewhere for users of the Rust Windows GNU toolchain on how to build crates such as this one. The rustup docs say "No additional software installation is necessary for basic use of the GNU build", and the installation instructions for this crate is `cargo install cargo-update`. Yet this crate will not build with this minimal setup. Is the user expected to

```
(try building) -> (decipher error messages) -> (install missing dependencies) -> (repeat until success)
```

?

But MSVC is the default and recommended toolchain on Windows, so maybe it's assumed the user knows what they're doing if they use the GNU toolchain. I had no experience with MSYS2, and so I had problems.

**Comment by torpak** [comment]
@Seeker14491 C++ dependencies don't really count as basic usage...
And what you describe is the typical way to build software that is not prepackaged.
You just notice it as painful because cargo without non-rust-dependencies is so damn effortless.

**Comment by torpak** [comment]
@nabijaczleweli Thank you very much for fixing this!

**Comment by nabijaczleweli** [comment]
"Is the user expected to install the required dependencies when provided with a clear error from the compiler?" Yes, yes it is.
