### ISSUE TITLE
Panic on cargo update

### ISSUE THREAD

**Issue by chrispickard** [nabijaczleweli/cargo-update#99]
This morning I ran `cargo install-update --git --all`  on my CentOS 7.5.1804 machine.
rustup info:
```
active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.32.0-nightly (13c943992 2018-11-18)
```
and got this panic
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -3, klass: 9, message: "object not found - no match for id (71434897673bf701aa2a9a55f1ec5740b6122a0d)" }', libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
   9: cargo_update::ops::GitRepoPackage::pull_version
  10: cargo_install_update::actual_main
  11: cargo_install_update::main
  12: std::rt::lang_start::{{closure}}
  13: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  14: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  15: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  16: main
  17: __libc_start_main
  18: <unknown>
```

**Comment by nabijaczleweli** [comment]
Before I try pushing anything code-wise, what git packages do you have?

**Comment by chrispickard** [comment]
what git packages in cargo? I'm not sure how to figure that out

**Comment by hcpl** [comment]
@chrispickard there should be a `~/.cargo/.crates.toml` which stores every crate installed via `cargo install`, so `grep 'git+' ~/.cargo/.crates.toml` should work.

**Comment by chrispickard** [comment]
```
$ grep 'git+' ~/.cargo/.crates.toml
"ion-shell 1.0.0-alpha (git+https://gitlab.redox-os.org/redox-os/ion/#0bff9e12ff3cc120b757a56266bd0b379f0510e6)" = ["ion"]

```

**Comment by hcpl** [comment]
Googling with the error message "object not found - no match for id" lead to this: https://github.com/rust-lang/cargo/issues/3561. It looks like the same problem (corrupt git repo somewhere), but your case is likely not originated from `cargo` (that issue was supposedly fixed in https://github.com/rust-lang/cargo/pull/5110).

Here is the `GitRepoPackage::pull_version()` latest source:

https://github.com/nabijaczleweli/cargo-update/blob/108f6aaa12d9846bea1de89184ec1168248a5b4b/src/ops/mod.rs#L354-L374

There are three `unwrap`s:
* On `fs::create_dir_all(...)` --- definitely not the culprit.
* On `r.find_remote("origin").and_then(...)`.
* On `r.set_head("FETCH_HEAD")`.

So the error comes from either of the last two.

**Comment by nabijaczleweli** [comment]
@chrispickard Would you mind running the problematic command after applying the following patch?

```diff
diff --git a/src/ops/mod.rs b/src/ops/mod.rs
index 9bae6ac97..2506f49b1 100644
--- a/src/ops/mod.rs
+++ b/src/ops/mod.rs
@@ -352,13 +352,13 @@ impl GitRepoPackage {
 
     /// Clone the repo and check what the latest commit's hash is.
     pub fn pull_version<P: AsRef<Path>>(&mut self, temp_dir: P) {
-        fs::create_dir_all(temp_dir.as_ref()).unwrap();
+        fs::create_dir_all(temp_dir.as_ref()).expect("temp dir creation");
         let clone_dir = temp_dir.as_ref().join(&self.name);
         let repo = if clone_dir.exists() {
             let mut r = git2::Repository::open(clone_dir);
             if let Ok(ref mut r) = r.as_mut() {
-                r.find_remote("origin").and_then(|mut rm| rm.fetch(&[self.branch.as_ref().map(String::as_str).unwrap_or("master")], None, None)).unwrap();
-                r.set_head("FETCH_HEAD").unwrap();
+                r.find_remote("origin").and_then(|mut rm| rm.fetch(&[self.branch.as_ref().map(String::as_str).unwrap_or_else(|| {println!("branch fallback"); "master"})], None, None)).expect("origin fetching");
+                r.set_head("FETCH_HEAD").expect("head setting");
             }
             r
         } else {
@@ -370,7 +370,7 @@ impl GitRepoPackage {
             bldr.clone(&self.url, &clone_dir)
         };
 
-        self.newest_id = Some(repo.and_then(|r| r.head().and_then(|h| h.target().ok_or_else(|| GitError::from_str("HEAD not a direct reference")))).unwrap());
+        self.newest_id = Some(repo.and_then(|r| r.head().and_then(|h| h.target().ok_or_else(|| GitError::from_str("HEAD not a direct reference")))).expect("origin fetching"));
     }
 
     /// Check whether this package needs to be installed
```

@hcpl thanks for guiding OP in these trying times 💜

**Comment by hcpl** [comment]
Oh shoot, I didn't notice the fourth `unwrap` :man_facepalming:

Anyway, I made a little more progress on this matter. The error message "object not found - no match for id (...)" comes from https://github.com/libgit2/libgit2/blob/771dfd1dd1c27a4693dfdfea521c07e72f456b29/src/odb.c#L1111 (this is the libgit2 commit that `libgit2-sys` crate tracks).

And that's it. I can't reproduce the error, presumably because `cargo-update` accesses git repos that are fine on my side, so I don't know where to investigate further (even if I know there are 3 potential entry points) :(.

> @hcpl thanks for guiding OP in these trying times :purple_heart:

No problem!

**Comment by chrispickard** [comment]
Thanks for all your help everyone, I'm no longer getting this panic, so I'm closing this issue
